set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:~/.local/bin"

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB,xterm-kitty:RGB"
set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on

set -s extended-keys off
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g history-limit 1000000
setw -g mode-keys vi


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Continuum & Resurrect Settings
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
set -g @resurrect-capture-pane-contents 'on'

# Auto-install TPM and plugins if not present
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

run '~/.config/tmux/plugins/tpm/tpm'
set -g status-justify "left"
set -g status-position top
