[general]
editor=nvim
#unsafe-accounts-conf=false

[ui]
index-columns=date>=,name<20%,flags:4,subject
column-flags={{.Flags | join ""}}
column-name={{index (.From | names) 0}}
column-subject={{.ThreadPrefix}}{{.Subject}}
column-date={{dateFormat .Date.Local "Jan 02"}}
column-separator="  "
sidebar-width=25
mouse-enabled=true
dirlist-left={{if eq .Folder "INBOX"}}   󰇮   {{else if eq .Folder "Sent"}}      {{else if eq .Folder "Drafts"}}   󰏫   {{else if eq .Folder "Archive"}}   󰄵   {{else if eq .Folder "Trash"}}   󰩹   {{else if eq .Folder "Junk"}}   󰒝   {{else}}   󰉋   {{end}}{{.Folder}}
dirlist-tree=true
styleset-name=tokyonight
threading-enabled=true
thread-prefix-tip = "❯ "
thread-prefix-indent = "  "
thread-prefix-stem = "│ "
thread-prefix-has-siblings = "├─"
thread-prefix-last-sibling = "└─"

icon-unencrypted=
icon-encrypted=✔
icon-signed=✔
icon-signed-encrypted=✔
icon-unknown=✘
icon-invalid=⚠

[statusline]
status-columns=left<*,center:=,right>*
column-left={{.Account}}  {{.StatusInfo}}
column-center={{.PendingKeys}}
column-right={{.TrayInfo}}  {{cwd}}
column-separator="  "

[viewer]
alternatives=text/plain,text/html
max-mime-height = 2

[compose]
header-layout = From,To,Cc,Subject

[multipart-converters]

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=html-render | colorize
.headers=colorize

[openers]
#text/html=open
#image/*=open

[hooks]

[templates]
